2024-08-25 20:05:08.851513: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x104a501d0>: Failed to resolve 'proxylist.geonode.com' ([Errno 8] nodename nor servname provided, or not known)"))
2024-08-25 20:05:08.851801: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:41:34.662817: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:41:34.664958: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:45:44.714127: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:45:44.714457: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:45:47.618853: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:45:47.619142: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:46:09.287788: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:46:09.288097: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:46:35.301575: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:46:35.301981: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
2024-09-02 04:47:17.382300: Exception in getRequest() https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc: HTTPSConnectionPool(host='proxylist.geonode.com', port=443): Max retries exceeded with url: /api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
2024-09-02 04:47:17.382868: Exception in getProxyListFromGeonode(): Sorry, no numbers below zero
